
const Data = {
     productItems:[
         {
             id: '1',
             name: 'Rolex',
             price: 39500,
             image: require('./pd1.jpeg').default,
             color: 'Pink',
             level: 'High',
         },
         {
            id: '2',
            name: 'BVLGARI',
            price: 2800,
            image: require('./pd2.jpeg').default,
            color: 'White',
            level: 'Low',
        },
        {
            id: '3',
            name: 'Dior',
            price: 6500,
            image: require('./pd3.jpeg').default,
            color: 'Gold',
            level: 'Medium',
        },
        {
            id: '4',
            name: 'Gucci',
            price: 9400,
            image: require('./pd4.jpeg').default,
            color: 'Gold',
            level: 'Medium',
        },
        {
            id: '5',
            name: 'Cartier',
            price: 50000,
            image: require('./pd5.jpeg').default,
            color: 'Pink',
            level: 'High',
        },
        {
            id: '6',
            name: 'Hublot',
            price: 33000,
            image: require('./pd6.jpeg').default,
            color: 'Silver',
            level: 'High',
        },
        {
            id: '7',
            name: 'Hermes',
            price: 25000,
            image: require('./pd7.jpeg').default,
            color: 'Gold',
            level: 'High',
        },
        {
            id: '8',
            name: 'Omega',
            price: 5700,
            image: require('./pd8.jpeg').default,
            color: 'White',
            level: 'Medium',
        },
        {
            id: '9',
            name: 'Daniel Wellington',
            price: 1000,
            image: require('./pd9.jpeg').default,
            color: 'Gold',
            level: 'Low',
        },
        {
            id: '10',
            name: 'Seiko',
            price: 1900,
            image: require('./pd10.jpeg').default,
            color: 'Gold',
            level: 'Low',
        },
        {
            id: '11',
            name: 'Zenith',
            price: 2100,
            image: require('./pd11.jpeg').default,
            color: 'Pink',
            level: 'Low',
        },
        {
            id: '12',
            name: 'Oris',
            price: 4500,
            image: require('./pd12.jpeg').default,
            color: 'Silver',
            level: 'Low',
        },
        {
            id: '13',
            name: 'Blancpain',
            price: 6300,
            image: require('./pd13.jpeg').default,
            color: 'Gold',
            level: 'Medium',
        },
        {
            id: '14',
            name: 'Philip Stein',
            price: 3800,
            image: require('./pd14.jpeg').default,
            color: 'White',
            level: 'Low',
        },
        {
            id: '15',
            name: 'Charriol',
            price: 1500,
            image: require('./pd15.jpeg').default,
            color: 'Gold',
            level: 'Low',
        },
     ],
};

export default Data;